# Placeholder for future Linux workstation
# Example NixOS configuration
{ config, pkgs, ... }:
{
  # This is a placeholder configuration for a future Linux workstation
  # Uncomment and customize when setting up a NixOS machine

  # networking.hostName = "linux-workstation";

  # Hardware configuration (generated by nixos-generate-config)
  # imports = [ ./hardware-configuration.nix ];

  # User configuration
  # users.users.wikigen = {
  #   isNormalUser = true;
  #   extraGroups = [ "wheel" "networkmanager" "docker" ];
  #   home = "/home/wikigen";
  # };

  # Desktop environment (example)
  # services.xserver.enable = true;
  # services.xserver.displayManager.gdm.enable = true;
  # services.xserver.desktopManager.gnome.enable = true;
}
